### ISSUE TITLE
BUG: An error will occur when player name includes non-Unicode character in `challonge.participants.create`

### ISSUE THREAD

**Issue by purerosefallen** [Tidwell/node-challonge#36]
`_http_client.js:105
      throw new ERR_UNESCAPED_CHARACTERS('Request path');
      ^

TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:105:13)
    at Object.request (https.js:272:10)
    at exports.Participants.Client.makeRequest (/mnt/c/ygo/ygopro-server/node_modules/challonge/lib/api/client.js:106:20)
    at exports.Participants.Participants.create (/mnt/c/ygo/ygopro-server/node_modules/challonge/lib/api/participants.js:79:7)
    at UploadToChallonge (/mnt/c/ygo/ygopro-server/ygopro-tournament.js:157:32)
    at Server.<anonymous> (/mnt/c/ygo/ygopro-server/ygopro-tournament.js:273:20)
    at Server.emit (events.js:182:13)
    at parserOnIncoming (_http_server.js:658:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)`

**Comment by purerosefallen** [comment]
I'm not sure if other functions which asks for player name has the same issue. However, it's very common that name may include non-Unicode character in non-English-speaking countries. I hope this would be solve soon.
