### ISSUE TITLE
BUG: ETIMEOUT

### ISSUE THREAD

**Issue by purerosefallen** [Tidwell/node-challonge#41]
Error: connect ETIMEDOUT 104.17.212.3:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
Error: socket hang up
    at createHangUpError (_http_client.js:322:15)
    at TLSSocket.socketOnEnd (_http_client.js:425:23)
    at TLSSocket.emit (events.js:187:15)
    at TLSSocket.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1094:12)
    at args.(anonymous function) (/usr/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:133:29)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Sometimes i get this error when uploading scores, and the whole server crashed.

**Comment by purerosefallen** [comment]
Could you please give me a reply?

**Comment by Tidwell** [comment]
This is fixed in version `2.2.0` just published to npm.

You can add a `timeout` param to your configuration when calling createClient that will enable error handling for timeouts.

The error will have a statusCode of 'timeout'
